### ISSUE TITLE
update broken links in Readme

### ISSUE THREAD

**Issue by Johannes-Sahlmann** [agabrown/PyGaia#13]
Some of the links in the Readme are broken, e.g. the link to https://github.com/agabrown/PyGaia/blob/master/pygaia/astrometry/coordinates.py

This probably stems from reorganising the package structure with a /src folder, since e.g. this link works:
https://github.com/agabrown/PyGaia/blob/master/src/pygaia/astrometry/coordinates.py

**Comment by agabrown** [comment]
Thanks for noticing. The links are fixed.
