### ISSUE TITLE
Missing requirements ujson, cartopy

### ISSUE THREAD

**Issue by mfouesneau** [agabrown/PyGaia#7]
https://github.com/agabrown/PyGaia/blob/90f05263e58623294ac1f48d33f9d4d784e02b55/src/pygaia/errors/spectroscopic.py#L8

https://github.com/agabrown/PyGaia/blob/90f05263e58623294ac1f48d33f9d4d784e02b55/src/pygaia/plot/sky.py#L4

ujson, cartopy are missing from the project requirements.

**Comment by agabrown** [comment]
Fixed in pyproject.toml and README
