### ISSUE TITLE
Case sensitive band name

### ISSUE THREAD

**Issue by mfouesneau** [agabrown/PyGaia#8]
Inconsistency between doc and code: the band's name is case-sensitive.

https://github.com/agabrown/PyGaia/blob/90f05263e58623294ac1f48d33f9d4d784e02b55/src/pygaia/errors/photometric.py#L180

https://github.com/agabrown/PyGaia/blob/90f05263e58623294ac1f48d33f9d4d784e02b55/src/pygaia/errors/photometric.py#L196

You could force the lower case to help
```code
f"logU_{_nobs_drs_bands[release][band]}"
```

```code
f"logU_{_nobs_drs_bands[release.lower()][band.lower()]}"
```

**Comment by agabrown** [comment]
Fixed. Thaks for the suggestion!
